name: merge_tagged_to_develop
on:
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/merge_stg_to_dev
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
