name: tagpr
on:
  push:
    branches: ["staging"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo $tag
        env:
          tag: ${{ steps.tagpr.outputs.tag }}
      - uses: ./.github/actions/merge_stg_to_dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo 'check'
